//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplRight
    {
        public int Right_ID { get; set; }
        public int ID_User { get; set; }
        public string Description { get; set; }
    
        public virtual ApplUser ApplUser { get; set; }
    }
}
