//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int ID_Guest { get; set; }
        public long CardNr { get; set; }
        public string CardHolder { get; set; }
        public string CardType { get; set; }
        public short CVCCode { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
