//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public Guest()
        {
            this.CreditCards = new HashSet<CreditCard>();
            this.Ratings = new HashSet<Rating>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Guest_ID { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Phone { get; set; }
        public string Street { get; set; }
        public string Zip { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual ICollection<CreditCard> CreditCards { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
