//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ID_Reservation { get; set; }
        public int ID_Guest { get; set; }
        public int ID_Room { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<byte> Location { get; set; }
        public Nullable<byte> Service { get; set; }
        public string Rating1 { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
