//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.Ratings = new HashSet<Rating>();
        }
    
        public int Reservation_ID { get; set; }
        public Nullable<int> ID_Room { get; set; }
        public Nullable<int> ID_Guest { get; set; }
        public Nullable<int> ID_TravelOffice { get; set; }
        public Nullable<int> ID_Hotel { get; set; }
        public Nullable<System.DateTime> DateCheckIn { get; set; }
        public Nullable<System.DateTime> DataCheckOut { get; set; }
        public Nullable<bool> Canceled { get; set; }
        public Nullable<bool> CheckedOut { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual Room Room { get; set; }
        public virtual TravelOffice TravelOffice { get; set; }
    }
}
