//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Reservations = new HashSet<Reservation>();
            this.RoomFeatures = new HashSet<RoomFeature>();
        }
    
        public int Room_ID { get; set; }
        public Nullable<int> ID_Hotel { get; set; }
        public string RoomNr { get; set; }
        public string Floor { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<RoomFeature> RoomFeatures { get; set; }
    }
}
